{{- if .Values.clickhouse.enabled -}}
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: {{ .Values.internal.clickhouse.host }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
spec:
  configuration:
    {{- if .Values.zookeeper.enabled }}
    zookeeper:
      nodes:
        - host: zookeeper
          port: {{ .Values.zookeeper.service.ports.client }}
    {{- end }}
    clusters:
      - name: {{ .Values.clickhouse.clusterName }}
        layout:
          shardsCount: 1
          replicasCount: {{ .Values.clickhouse.replicas }}
    users:
      app/profile: default
      app/quota: default
      app/networks/ip:
        - "::/0"
        - 0.0.0.0/0
      app/grants/query: GRANT ALL ON *.*
      app/password:
        valueFrom:
          secretKeyRef:
            name: {{ include "posthog.secretName" . }}
            key: {{ .Values.secrets.keys.clickhousePassword }}
      api/profile: default
      api/quota: default
      api/networks/ip:
        - "::/0"
        - 0.0.0.0/0
      api/password: apipass
    settings:
      kafka_hosts: {{ tpl .Values.clickhouse.config.kafkaHosts . | quote }}
      macros/hostClusterType: {{ .Values.clickhouse.macros.hostClusterType | quote }}
      macros/hostClusterRole: {{ .Values.clickhouse.macros.hostClusterRole | quote }}
    files:
      config.d/posthog_named_collections.xml: |
        <clickhouse>
          <named_collections>
          {{- range .Values.clickhouse.namedCollections }}
            <{{ . }}>
              <kafka_broker_list>{{ tpl $.Values.clickhouse.config.kafkaHosts $ }}</kafka_broker_list>
            </{{ . }}>
          {{- end }}
          </named_collections>
        </clickhouse>
  defaults:
    templates:
      podTemplate: clickhouse
      dataVolumeClaimTemplate: data
  templates:
    podTemplates:
      - name: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: {{ .Values.clickhouse.image | quote }}
    volumeClaimTemplates:
      - name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.storage | quote }}
{{- end }}
