apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "posthog.fullname" . }}-proxy
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {{ default .Values.global.domain .Values.ingress.host }} {
      {{- with .Values.routing.objectStorageRoute }}
      {{- if and .enabled (eq $.Values.profile.mode "bundled") }}
      handle {{ default (printf "/%s" (include "posthog.objectStorageBucket" $)) .path }}* {
        reverse_proxy {{ tpl .host $ }}:{{ .port }}
      }
      {{- end }}
      {{- end }}
      {{- range .Values.routing.routes }}
      {{- if eq .path "/" }}
      handle {
        reverse_proxy {{ include "posthog.serviceHost" (dict "root" $ "name" .service) }}:{{ .port }}
      }
      {{- else }}
      handle {{ .path }}* {
        {{- if .stripPrefix }}
        uri strip_prefix {{ .path }}
        {{- end }}
        reverse_proxy {{ include "posthog.serviceHost" (dict "root" $ "name" .service) }}:{{ .port }}{{ if .stripPrefix }} {
          flush_interval -1
        }{{ end }}
      }
      {{- end }}
      {{- end }}
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "posthog.fullname" . }}-temporal-dynamicconfig
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
data:
  development-sql.yaml: |
    limit.maxIDLength:
      - value: 255
        constraints: {}
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
        constraints: {}
    system.visibilityDisableOrderByClause:
      - value: false
        constraints: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "posthog.fullname" . }}-livestream
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
data:
  configs.yml: |
    topics:
      - events_plugin_ingestion
