{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "posthog.secretName" . }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.secretKey }}: {{ default (randAlphaNum 50) .Values.secrets.values.secretKey | quote }}
  {{ .Values.secrets.keys.encryptionSaltKeys }}: {{ default (randAlphaNum 32) .Values.secrets.values.encryptionSaltKeys | quote }}
  {{ .Values.secrets.keys.clickhousePassword }}: {{ .Values.secrets.values.clickhousePassword | quote }}
  {{ .Values.secrets.keys.objectStorageAccessKey }}: {{ .Values.secrets.values.objectStorageAccessKey | quote }}
  {{ .Values.secrets.keys.objectStorageSecretKey }}: {{ .Values.secrets.values.objectStorageSecretKey | quote }}
  {{ .Values.secrets.keys.sessionRecordingAccessKey }}: {{ .Values.secrets.values.sessionRecordingAccessKey | quote }}
  {{ .Values.secrets.keys.sessionRecordingSecretKey }}: {{ .Values.secrets.values.sessionRecordingSecretKey | quote }}
  {{ .Values.secrets.keys.captureLogsJwtSecret }}: {{ default (randAlphaNum 32) .Values.secrets.values.captureLogsJwtSecret | quote }}
  {{ .Values.secrets.keys.livestreamJwtSecret }}: {{ default (randAlphaNum 32) .Values.secrets.values.livestreamJwtSecret | quote }}
  {{ .Values.secrets.keys.internalApiSecret }}: {{ default (randAlphaNum 32) .Values.secrets.values.internalApiSecret | quote }}
{{- end }}
